version: '3.7'
services:
    nginx:
        image: nginx:1.17.8
        container_name: nginx
        depends_on:
            - frontend
            - api
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - wv-network
        ports:
            - 80:80
    frontend:
        build:
            context: ./frontend_server
            dockerfile: Dockerfile
        image: wv-frontend
        container_name: wv-frontend
        volumes:
            - ./frontend_server:/app/
        networks:
            wv-network:
                aliases:
                    - wv-frontend
    api:
        build:
            context: ./api_server
            dockerfile: Dockerfile
        image: wv-api
        container_name: wv-api
        volumes:
            - ./api_server:/app/
        networks:
            wv-network:
                aliases:
                    - wv-api
networks:
    wv-network: