version: '3.7'
services:
    nginx:
        image: nginx:1.17.8
        container_name: nginx
        restart: unless-stopped
        depends_on:
            - frontend
            - api
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/certbot/conf:/etc/letsencrypt
            - ./conf/certbot/www:/var/www/certbot
        networks:
            - wv-network
        ports:
            - 80:80
            - 443:443
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    frontend:
        build:
            context: ./frontend_server
            dockerfile: Dockerfile
        image: wv-frontend
        container_name: wv-frontend
        volumes:
            - ./frontend_server:/app/
        networks:
            wv-network:
                aliases:
                    - wv-frontend
    api:
        build:
            context: ./api_server
            dockerfile: Dockerfile
        image: wv-api
        container_name: wv-api
        volumes:
            - ./api_server:/app/
            - ./api_server/supervisord.conf:/etc/supervisord.conf
        networks:
            wv-network:
                aliases:
                    - wv-api
    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            - nginx
        restart: unless-stopped
        volumes:
            - ./conf/certbot/conf:/etc/letsencrypt
            - ./conf/certbot/www:/var/www/certbot
        networks:
            - wv-network
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
    wv-network: